# Generated by Django 3.0 on 2020-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
    ]
